-- 20260821_initial
--
-- ไฟล์นี้เป็น "เอกสารประกอบ" ของ schema ตั้งต้นเท่านั้น
-- การสร้างตารางจริงทำโดย gormigrate ที่ main.go (migration id: 20260821_initial)
-- ซึ่งรันอัตโนมัติตอน service เริ่มทำงาน — ไม่ต้องรันไฟล์นี้เอง
--
-- ใช้ไฟล์นี้เพื่อทบทวน schema และเป็นที่บันทึกการแก้ schema แบบมือในอนาคต
-- (ตั้งชื่อไฟล์ใหม่เป็น YYYYMMDD_description.sql)

-- ตารางที่ถูกสร้างโดย migration ตั้งต้น:
--
--   users                  บัญชีผู้ใช้ (email + google)          F-02
--   verification_codes     OTP สมัคร/รีเซ็ตรหัสผ่าน
--   organizations          บัญชีบริษัท                            F-05
--   organization_members   สมาชิกองค์กร + role                     F-05
--   teams                  ชุดพนักงานที่เก็บไว้ใช้ซ้ำ              F-25
--   team_members           เชื่อม team ↔ profile                   F-25
--   profiles               ข้อมูลดวงรายบุคคล (ระบบ memory)        F-25, F-07, F-08
--   orders                 คำสั่งซื้อรายงาน
--   reports                ผลลัพธ์รายฉบับ                          F-20, F-21, F-23, F-24, F-27
--   consents               บันทึกการยอมรับเงื่อนไข                 F-06
--   legal_documents        เอกสารกฎหมายแบบมีเวอร์ชัน               F-01

-- ── ดัชนีเพิ่มเติมที่อาจต้องใส่เมื่อข้อมูลโตขึ้น ──────────────────
-- ยังไม่เพิ่มตอนนี้เพราะปริมาณข้อมูลยังน้อย และดัชนีที่ไม่ได้ใช้มีต้นทุนตอนเขียน
--
-- CREATE INDEX idx_orders_user_status  ON orders (user_id, status);
-- CREATE INDEX idx_profiles_org_kind   ON profiles (organization_id, kind);
-- CREATE INDEX idx_reports_order_ver   ON reports (order_id, version DESC);

-- ── หมายเหตุ PDPA ────────────────────────────────────────────────
-- profiles เก็บวัน–เวลา–สถานที่เกิด ซึ่งเป็นข้อมูลส่วนบุคคล
-- และในกรณีที่องค์กรกรอกข้อมูลของ candidate จะเป็นข้อมูลของบุคคลที่สาม
-- (คอลัมน์ consent_source บันทึกไว้ว่ามาจากตัวเจ้าของข้อมูลเองหรือไม่)
--
-- ระยะเวลาเก็บรักษาและขั้นตอนการลบยังไม่สรุป — ต้องได้ข้อสรุปจาก F-01 ก่อน
-- แล้วจึงเพิ่ม job ลบข้อมูลตามกำหนด
